language: php

before_script:
  - composer self-update
  - composer install --dev --prefer-source

php:
  - 7.1
  - 7.2
  #- hhvm Not possible due to https://github.com/facebook/hhvm/issues/6954

script:
  - phpunit --coverage-text
